// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BackButtonController from "./back_button_controller"
application.register("back-button", BackButtonController)

import FollowsController from "./follows_controller"
application.register("follows", FollowsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)

import ProfileTabsController from "./profile_tabs_controller"
application.register("profile-tabs", ProfileTabsController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import VotesHandlerController from "./votes_handler_controller"
application.register("votes-handler", VotesHandlerController)
