// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FollowMoviesController from "./follow_movies_controller"
application.register("follow-movies", FollowMoviesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import VotesHandlerController from "./votes_handler_controller"
application.register("votes-handler", VotesHandlerController)
